/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package my.memo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ResourcedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Memo service. Represents a row in the &quot;memo_Memo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>my.memo.model.impl.MemoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>my.memo.model.impl.MemoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Memo
 * @generated
 */
@ProviderType
public interface MemoModel
	extends BaseModel<Memo>, ContainerModel, GroupedModel, ResourcedModel,
			ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a memo model instance should use the {@link Memo} interface instead.
	 */

	/**
	 * Returns the primary key of this memo.
	 *
	 * @return the primary key of this memo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this memo.
	 *
	 * @param primaryKey the primary key of this memo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the memo ID of this memo.
	 *
	 * @return the memo ID of this memo
	 */
	public long getMemoId();

	/**
	 * Sets the memo ID of this memo.
	 *
	 * @param memoId the memo ID of this memo
	 */
	public void setMemoId(long memoId);

	/**
	 * Returns the resource prim key of this memo.
	 *
	 * @return the resource prim key of this memo
	 */
	@Override
	public long getResourcePrimKey();

	/**
	 * Sets the resource prim key of this memo.
	 *
	 * @param resourcePrimKey the resource prim key of this memo
	 */
	@Override
	public void setResourcePrimKey(long resourcePrimKey);

	@Override
	public boolean isResourceMain();

	/**
	 * Returns the group ID of this memo.
	 *
	 * @return the group ID of this memo
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this memo.
	 *
	 * @param groupId the group ID of this memo
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this memo.
	 *
	 * @return the company ID of this memo
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this memo.
	 *
	 * @param companyId the company ID of this memo
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this memo.
	 *
	 * @return the user ID of this memo
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this memo.
	 *
	 * @param userId the user ID of this memo
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this memo.
	 *
	 * @return the user uuid of this memo
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this memo.
	 *
	 * @param userUuid the user uuid of this memo
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this memo.
	 *
	 * @return the user name of this memo
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this memo.
	 *
	 * @param userName the user name of this memo
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this memo.
	 *
	 * @return the create date of this memo
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this memo.
	 *
	 * @param createDate the create date of this memo
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this memo.
	 *
	 * @return the modified date of this memo
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this memo.
	 *
	 * @param modifiedDate the modified date of this memo
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the text of this memo.
	 *
	 * @return the text of this memo
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this memo.
	 *
	 * @param text the text of this memo
	 */
	public void setText(String text);

	/**
	 * Returns the version of this memo.
	 *
	 * @return the version of this memo
	 */
	public int getVersion();

	/**
	 * Sets the version of this memo.
	 *
	 * @param version the version of this memo
	 */
	public void setVersion(int version);

	/**
	 * Returns the summary of this memo.
	 *
	 * @return the summary of this memo
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this memo.
	 *
	 * @param summary the summary of this memo
	 */
	public void setSummary(String summary);

	/**
	 * Returns the latest of this memo.
	 *
	 * @return the latest of this memo
	 */
	public boolean getLatest();

	/**
	 * Returns <code>true</code> if this memo is latest.
	 *
	 * @return <code>true</code> if this memo is latest; <code>false</code> otherwise
	 */
	public boolean isLatest();

	/**
	 * Sets whether this memo is latest.
	 *
	 * @param latest the latest of this memo
	 */
	public void setLatest(boolean latest);

	/**
	 * Returns the main of this memo.
	 *
	 * @return the main of this memo
	 */
	public boolean getMain();

	/**
	 * Returns <code>true</code> if this memo is main.
	 *
	 * @return <code>true</code> if this memo is main; <code>false</code> otherwise
	 */
	public boolean isMain();

	/**
	 * Sets whether this memo is main.
	 *
	 * @param main the main of this memo
	 */
	public void setMain(boolean main);

	/**
	 * Returns the status of this memo.
	 *
	 * @return the status of this memo
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this memo.
	 *
	 * @param status the status of this memo
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this memo.
	 *
	 * @return the status by user ID of this memo
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this memo.
	 *
	 * @param statusByUserId the status by user ID of this memo
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this memo.
	 *
	 * @return the status by user uuid of this memo
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this memo.
	 *
	 * @param statusByUserUuid the status by user uuid of this memo
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this memo.
	 *
	 * @return the status by user name of this memo
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this memo.
	 *
	 * @param statusByUserName the status by user name of this memo
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this memo.
	 *
	 * @return the status date of this memo
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this memo.
	 *
	 * @param statusDate the status date of this memo
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this memo is approved.
	 *
	 * @return <code>true</code> if this memo is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this memo is denied.
	 *
	 * @return <code>true</code> if this memo is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this memo is a draft.
	 *
	 * @return <code>true</code> if this memo is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this memo is expired.
	 *
	 * @return <code>true</code> if this memo is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this memo is inactive.
	 *
	 * @return <code>true</code> if this memo is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this memo is incomplete.
	 *
	 * @return <code>true</code> if this memo is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this memo is pending.
	 *
	 * @return <code>true</code> if this memo is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this memo is scheduled.
	 *
	 * @return <code>true</code> if this memo is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	/**
	 * Returns the container model ID of this memo.
	 *
	 * @return the container model ID of this memo
	 */
	@Override
	public long getContainerModelId();

	/**
	 * Sets the container model ID of this memo.
	 *
	 * @param containerModelId the container model ID of this memo
	 */
	@Override
	public void setContainerModelId(long containerModelId);

	/**
	 * Returns the container name of this memo.
	 *
	 * @return the container name of this memo
	 */
	@Override
	public String getContainerModelName();

	/**
	 * Returns the parent container model ID of this memo.
	 *
	 * @return the parent container model ID of this memo
	 */
	@Override
	public long getParentContainerModelId();

	/**
	 * Sets the parent container model ID of this memo.
	 *
	 * @param parentContainerModelId the parent container model ID of this memo
	 */
	@Override
	public void setParentContainerModelId(long parentContainerModelId);

	@Override
	public Memo cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}